### ISSUE TITLE
Bug: Resolve circular imports

### ISSUE THREAD

**Issue by skvaris** [AngelicAxolotl/CodeJam#20]
`axolotic/tui/tui.py` imports `axolotic/tui/screens/*.py`. In turn they import `axolotic/tui/tui.py` to use `Tui` in type hints.

To solve we could:

1. Use strings as type hints: `parent: Tui` -> `parent: 'axolotic.tui.tui.Tui`
2. decouple the Screens from the `Tui` class by moving the whole Screen and argument setup into `axolotic/tui/__init__.py` or in a new module. Perhaps with factory.

**Comment by WatermelonSalt** [comment]
maybe we should move it into a new module, and if we are moving it into a new module I should also probably change the name of my issue that I claimed

**Comment by Donkere-vader** [comment]
I thing using a string approach is best in this case.

But imo just "Tui" is enough. If you want you can add the parent packages like

"axolotic.tui.Tui"

**Comment by skvaris** [comment]
The `TYPE_CHECKING` approach wont work. The type hints are evaluated, at least in 3.9. So it will show a `NameError`.

I think the string approach is the best.

**Comment by kedarr12** [comment]
`from __future__ import annotations` exists so a `NameError` is not raised
